### ISSUE TITLE
Including new DB structure in Muses SRM with hashed passwords

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/MusesSRM#22]
For now, we have the old version of startup_db.sql.

**Comment by unintendedbear** [comment]
Hi all @szamarripa @mrburvall @yasali @xaviertiti, 

we need this done as soon as possible, because if @jlmacal develops depending on old startup_db.sql, he will have to change many parts of the code later on. What's more, tables devices & users are not tied by any foreing key. For the trials dump, I found that I could link them by "name" in devices table and "username" in users table... but we should include a foreign key or something, because this does not happen for the dummy data. What do you think?

**Comment by mrburvall** [comment]
Hello Paloma,

Vahid used a script to add some user for the SRM, see
https://github.com/MusesProject/MusesSRM/blob/master/src/main/resources/eu/musesproject/db/db_tomcat_startup.sql
https://github.com/MusesProject/MusesSRM/blob/master/src/main/resources/eu/musesproject/db/db_tomcat_startup.sql

See also attached instructions.

Feel free to ask questions if needed.
Best regards, Markus

Den den 27 maj 2015 klockan 09:20 skrev Paloma de las Cuevas Delgado
notifications@github.com:

> Hi all @szamarripa https://github.com/szamarripa @mrburvall
> https://github.com/mrburvall @yasali https://github.com/yasali
> @xaviertiti https://github.com/xaviertiti ,
> 
> we need this done as soon as possible, because if @jlmacal
> https://github.com/jlmacal develops depending on old startup_db.sql, he
> will have to change many parts of the code later on. What's more, tables
> devices & users are not tied by any foreing key. For the trials dump, I
> found that I could link them by "name" in devices table and "username" in
> users table... but we should include a foreign key or something, because
> this does not happen for the dummy data. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MusesProject/MusesSRM/issues/22#issuecomment-105793738
> .

Instructions on how to set-up MusesSRM:
1) Install NetBeans
2) In case you forgot to enable the "install Tomcat" check-box during installation, then grab Tomcat from its website.
3) Make NetBeans aware of where Tomcat folder is: Netbeans > Tools > Servers > Add Server > Apache Tomcat > Browse to Tomcat folder > Open > Enter "musesadmin" as username and "musespass" as password.
4) Open the file at CATALIBA_HOME/conf/tomcat-users.xml in a text editor. Create a user called "musesadmin" with pass "musespass" and role "manager-script" inside this file. 
5) NetBeans > Window > Services > Servers > Apache Tomcat or TomEE > Right-click and choose start
6) In case Tomcat fails to start, remove the double quote on noJuliConfig and noJuliManager in CATALIBA_HOME/bin/catalina.bat. This is a bug http://stackoverflow.com/questions/22225764/starting-of-tomcat-failed-from-netbeans
7) In order to be able to login you need a user which is part of the "admin" role in the Tomcat Realm. Add that user in CATALIBA_HOME/conf/tomcat-users.xml.
8) Storing user credentials in xml files are not recommended so Tomcat Realm should be moved to database. Start by installing mysql.
9) Once mysql is installed, run the mysql script at MusesSRM/src/main/resources/eu/musesproject/db/db_tomcat_startup.sql
10) check if you have a database called "muses" in mysql. If it does not exist then run the mysql script at MusesSRM/src/main/resources/eu/musesproject/db/startup_db.sql
11) Place mysql-connector-java.jar in CATALIBA_HOME/lib/ even if you have it as a Maven dependency. 
12) Place the Realm tag bellow inside CATALIBA_HOME/conf/server.xml underneath the existing Realm tag. Feel free to modify the values if you have another configurations on your machine.

<Realm  className="org.apache.catalina.realm.JDBCRealm"
 driverName="com.mysql.jdbc.Driver"
 connectionURL="jdbc:mysql://localhost:3306/tomcat_realm"
 connectionName="tomcat"
 connectionPassword="tomcat"
 userTable="users"
 userNameCol="username"
 userCredCol="password"
 userRoleTable="users_roles"
 roleNameCol="rolename" 
 digest="SHA"/>

13) In Netbeans: Run > Run Project (MUSESSRM)
14) The browser should pop up and show the website. Try to login with user "musesadmin" and pass "musespass" if you ran the first database script above.
15) Troubleshooting: Right-click on the MUSESSRM project in Netbeans and choose Properties > Run. Make sure the value of the server is the correct Tomcat in case you have several of them.

**Comment by jlmacal** [comment]
Vale, parece que no lo pillan porque el init sigue con claves en plano, 
en principio lo unico que tiene las claves con los hashes activados son 
los usuarios del frontend. Luego les redacto comentando que no deberian 
almacenar las claves de los clientes en plano. Nos vemos!

**Comment by jlmacal** [comment]
Sorry, only for Paloma ;).

**Comment by jlmacal** [comment]
Hello, it doesn’t affects the frontend MusesSRM, but in my opinion the 
data collected from users should be encrypted and not in clear text.

For example

INSERT INTO `users` VALUES 
(1,'admin','admin','admin@muses.com','muses',_'asdfasdfefawef545'_,1,200,100,'en'…

instead of

INSERT INTO `users` VALUES 
(1,'admin','admin','admin@muses.com','muses','muses',1,200,100,'en'….
